import { contextBridge, ipcRenderer } from "electron";
import type { ApiMethod } from "../shared/types";
const methods = [
  "localCheckInfo",
  "localCheckState",
  "startLocalChecks",
  "stopLocalChecks",
  "pauseLocalChecks",
  "updateLocalCheckBuffer",
  "inspectLocalSymbol",
  "localBlame",
  "roomAccessInfo",
  "allowRoomAccess",
  "projectChatPresence",
  "stopProjectChatPending",
  "projectChatAgents",
  "projectChatAgent",
  "stopProjectChatAgent",
  "resolveStoppedWork",
  "projectChatShareInfo",
  "shareProjectChat",
  "syncProjectChat",
  "projectChatInvite",
  "sharedProjectChats",
  "openSharedProjectChat",
  "joinProjectConversation",
  "projects",
  "addProject",
  "createScratch",
  "scratchChats",
  "projectIcon",
  "projectGroups",
  "createProjectGroup",
  "renameProjectGroup",
  "removeProjectGroup",
  "moveProjectGroup",
  "moveProject",
  "renameProject",
  "revealProject",
  "linkProject",
  "triageProjectChat",
  "renameProjectChat",
  "forkProjectChat",
  "projectCommands",
  "projectBranchPulls",
  "projectCiStatus",
  "projectPreparePull",
  "projectCreatePull",
  "projectBranches",
  "projectChangeBranch",
  "projectFiles",
  "projectFile",
  "saveProjectFile",
  "projectWorkingTree",
  "projectTasks",
  "stopProjectTask",
  "restartProjectTask",
  "openTerminal",
  "writeTerminal",
  "prefillClaudeSignIn",
  "resizeTerminal",
  "ackTerminal",
  "adoptTerminal",
  "projectWorkingDiff",
  "projectTurnDiff",
  "projectHistory",
  "projectCommit",
  "projectCommitDiff",
  "rewindProjectTurn",
  "projectGitAction",
  "projectCommitMessage",
  "projectMergePlan",
  "projectMergeBranch",
  "projectDeleteBranch",
  "projectCatchUp",
  "projectPulls",
  "projectChats",
  "createProjectChat",
  "projectWorktree",
  "projectWorktreeDiff",
  "removeProjectWorktree",
  "revealProjectWorktree",
  "revealAgentWorktree",
  "projectChat",
  "projectChatImage",
  "projectChatReadImage",
  "revealProjectChatReadImage",
  "sendProjectChat",
  "cancelProjectChat",
  "startDeepReview",
  "resumeDeepReview",
  "resumeUltraplan",
  "setDeepReviewFinding",
  "resumeProjectChat",
  "compactProjectChat",
  "projectChatQueueAction",
  "respondProjectChat",
  "liveSyncState",
  "liveSyncStart",
  "liveSyncStop",
  "liveSyncConflict",
  "liveSyncResolve",
  "workingTree",
  "workingDiff",
  "gitAction",
  "gitInfo",
  "chooseGit",
  "resetGit",
  "roomHosting",
  "saveRoomHosting",
  "roomAcceptInvitation",
  "roomConnect",
  "roomState",
  "roomDisconnect",
  "roomPoll",
  "roomSend",
  "roomCancel",
  "roomPresence",
  "roomInvite",
  "roomMembers",
  "roomRevoke",
  "inspectSymbol",
  "projectCheckInfo",
  "projectCheckState",
  "startProjectChecks",
  "stopProjectChecks",
  "pauseProjectChecks",
  "updateCheckBuffer",
  "triageState",
  "startTriage",
  "cancelTriage",
  "groupPaths",
  "bootstrap",
  "retryLoginRestore",
  "cancelLoginRestore",
  "saveWorkspace",
  "connect",
  "disconnect",
  "search",
  "pull",
  "files",
  "contents",
  "blame",
  "reviews",
  "reviewComments",
  "discussion",
  "progress",
  "saveProgress",
  "submitReview",
  "reply",
  "resolveComment",
  "comment",
  "folder",
  "linkFolder",
  "readLocalFile",
  "saveLocalFile",
  "readClipboard",
  "writeClipboard",
  "writeClipboardImage",
  "launchCodex",
  "askAboutLines",
  "aiSettings",
  "saveAISettings",
  "devopsStatus",
  "saveDevOpsSettings",
  "devopsWorkItems",
  "providerUsage",
  "agentModels",
  "agentDefaults",
  "openExternal",
  "updateState",
  "downloadUpdate",
  "installUpdate",
  "applyAppearance",
  "setInterfaceScale",
  "searchThemes",
  "fetchThemes",
  "setBadge",
  "windowControl",
  "isMaximized",
  "parseUrl",
  "phoneRemoteState",
  "setPhoneRemote",
  "phonePairing",
  "phoneAppearance",
  "revokePhone",
] as const satisfies readonly ApiMethod[];
// Fails to compile, naming the method, when the Api gains one this list lacks.
const complete: Exclude<ApiMethod, (typeof methods)[number]> extends never
  ? true
  : Exclude<ApiMethod, (typeof methods)[number]> = true;
void complete;
const api = Object.fromEntries(
  methods.map((method) => [
    method,
    async (...args: unknown[]) => {
      const r = await ipcRenderer.invoke("relay:invoke", method, args);
      if (!r.ok) throw new Error(r.error);
      return r.value;
    },
  ]),
);
contextBridge.exposeInMainWorld("relay", {
  ...api,
  onProjectChat: (callback: (event: unknown) => void) => {
    const listener = (_event: unknown, value: unknown) => callback(value);
    ipcRenderer.on("relay:project-chat", listener);
    return () => ipcRenderer.removeListener("relay:project-chat", listener);
  },
  onUpdate: (callback: (state: unknown) => void) => {
    const listener = (_event: unknown, value: unknown) => callback(value);
    ipcRenderer.on("relay:update", listener);
    return () => ipcRenderer.removeListener("relay:update", listener);
  },
  onTerminal: (callback: (event: unknown) => void) => {
    const listener = (_event: unknown, value: unknown) => callback(value);
    ipcRenderer.on("relay:terminal", listener);
    return () => ipcRenderer.removeListener("relay:terminal", listener);
  },
  onMaximized: (callback: (maximized: boolean) => void) => {
    const listener = (_event: unknown, value: boolean) => callback(value);
    ipcRenderer.on("relay:maximized", listener);
    return () => ipcRenderer.removeListener("relay:maximized", listener);
  },
  onOpenUrl: (callback: (url: string) => void) => {
    const listener = (_event: unknown, url: string) => callback(url);
    ipcRenderer.on("relay:open-url", listener);
    return () => ipcRenderer.removeListener("relay:open-url", listener);
  },
});
