import { contextBridge, ipcRenderer, webUtils } from "electron";
import type { ApiMethod } from "../shared/types";
import type { RelayEvents } from "../shared/events";
const methods = [
  "localCheckInfo",
  "localCheckState",
  "startLocalChecks",
  "stopLocalChecks",
  "pauseLocalChecks",
  "updateLocalCheckBuffer",
  "inspectLocalSymbol",
  "localBlame",
  "roomAccessInfo",
  "allowRoomAccess",
  "projectChatPresence",
  "stopProjectChatPending",
  "projectChatAgents",
  "projectChatAgent",
  "stopProjectChatAgent",
  "resolveStoppedWork",
  "projectChatShareInfo",
  "shareProjectChat",
  "syncProjectChat",
  "projectChatInvite",
  "sharedProjectChats",
  "openSharedProjectChat",
  "joinProjectConversation",
  "projects",
  "addProject",
  "createScratch",
  "scratchChats",
  "projectIcon",
  "projectGroups",
  "createProjectGroup",
  "renameProjectGroup",
  "removeProjectGroup",
  "moveProjectGroup",
  "moveProject",
  "renameProject",
  "revealProject",
  "linkProject",
  "triageProjectChat",
  "renameProjectChat",
  "markProjectChatSeen",
  "forkProjectChat",
  "regenerateProjectChatTitle",
  "projectCommands",
  "projectBranchPulls",
  "projectCiStatus",
  "projectPreparePull",
  "projectCreatePull",
  "projectBranches",
  "projectChangeBranch",
  "projectFiles",
  "projectDirectory",
  "projectFileInfo",
  "projectImage",
  "projectThumbnail",
  "revealProjectPath",
  "openProjectPath",
  "projectAbsolutePath",
  "createProjectEntry",
  "renameProjectEntry",
  "trashProjectEntry",
  "projectFile",
  "saveProjectFile",
  "projectWorkingTree",
  "projectTasks",
  "stopProjectTask",
  "restartProjectTask",
  "openTerminal",
  "writeTerminal",
  "prefillClaudeSignIn",
  "resizeTerminal",
  "ackTerminal",
  "adoptTerminal",
  "projectWorkingDiff",
  "projectTurnDiff",
  "projectHistory",
  "projectCommit",
  "projectCommitDiff",
  "rewindProjectTurn",
  "projectGitAction",
  "projectCommitMessage",
  "nameReviewSetup",
  "projectPlanCommitSplit",
  "projectApplyCommitSplit",
  "projectMergePlan",
  "projectMergeBranch",
  "projectDeleteBranch",
  "projectCatchUp",
  "projectRebase",
  "projectPulls",
  "projectChats",
  "createProjectChat",
  "projectWorktree",
  "projectWorktreeDiff",
  "removeProjectWorktree",
  "projectWorktreeMove",
  "moveProjectChatToWorktree",
  "revealProjectWorktree",
  "revealAgentWorktree",
  "projectChat",
  "projectChatImage",
  "projectChatReadImage",
  "revealProjectChatReadImage",
  "revealProjectTurnFile",
  "sendProjectChat",
  "cancelProjectChat",
  "startDeepReview",
  "resumeDeepReview",
  "resumeUltraplan",
  "setDeepReviewFinding",
  "resumeProjectChat",
  "compactProjectChat",
  "projectChatQueueAction",
  "respondProjectChat",
  "liveSyncState",
  "liveSyncStart",
  "liveSyncStop",
  "liveSyncConflict",
  "liveSyncResolve",
  "workingTree",
  "workingDiff",
  "gitAction",
  "gitInfo",
  "chooseGit",
  "resetGit",
  "roomHosting",
  "saveRoomHosting",
  "roomAcceptInvitation",
  "roomConnect",
  "roomState",
  "roomDisconnect",
  "roomPoll",
  "roomSend",
  "roomCancel",
  "roomPresence",
  "roomInvite",
  "roomMembers",
  "roomRevoke",
  "inspectSymbol",
  "projectCheckInfo",
  "projectCheckState",
  "startProjectChecks",
  "stopProjectChecks",
  "pauseProjectChecks",
  "updateCheckBuffer",
  "triageState",
  "startTriage",
  "cancelTriage",
  "groupPaths",
  "bootstrap",
  "retryLoginRestore",
  "cancelLoginRestore",
  "saveWorkspace",
  "connect",
  "disconnect",
  "search",
  "pull",
  "files",
  "contents",
  "changedBetween",
  "blame",
  "reviews",
  "reviewComments",
  "discussion",
  "progress",
  "saveProgress",
  "submitReview",
  "reply",
  "resolveComment",
  "comment",
  "folder",
  "linkFolder",
  "readLocalFile",
  "saveLocalFile",
  "readClipboard",
  "writeClipboard",
  "writeClipboardImage",
  "launchCodex",
  "askAboutLines",
  "aiSettings",
  "saveAISettings",
  "smartProjectNames",
  "saveSmartProjectNames",
  "autoSettleDays",
  "saveAutoSettleDays",
  "saveSidebarView",
  "newThreadAgent",
  "saveNewThreadAgent",
  "newThreadModels",
  "saveNewThreadModel",
  "devopsStatus",
  "saveDevOpsSettings",
  "devopsWorkItems",
  "devopsConnection",
  "devopsFields",
  "plugins",
  "setPluginEnabled",
  "clockifyStatus",
  "saveClockifySettings",
  "clockifyWorkspaces",
  "clockifyProjects",
  "clockifyTimer",
  "clockifyTouch",
  "saveClockifyReview",
  "describeClockifyReview",
  "submitClockifyReview",
  "discardClockifyReview",
  "providerUsage",
  "agentModels",
  "agentDefaults",
  "openExternal",
  "updateState",
  "checkForUpdates",
  "downloadUpdate",
  "installUpdate",
  "releaseNotes",
  "dictationState",
  "downloadDictationModel",
  "cancelDictationDownload",
  "removeDictationModel",
  "dictationMicrophone",
  "connectDictation",
  "warmDictation",
  "agentVersions",
  "linkAgent",
  "unlinkAgent",
  "sourceControl",
  "setSourceControlEnabled",
  "linkSourceControlCli",
  "unlinkSourceControlCli",
  "teaSetup",
  "connectWithTea",
  "signInCursor",
  "signOutCursor",
  "checkAgentVersions",
  "updateAgent",
  "applyAppearance",
  "tintTitleBar",
  "setInterfaceScale",
  "setMenuShortcuts",
  "ignoreMenuShortcuts",
  "searchThemes",
  "fetchThemes",
  "setBadge",
  "windowControl",
  "isMaximized",
  "parseUrl",
  "phoneRemoteState",
  "setPhoneRemote",
  "phonePairing",
  "phoneAppearance",
  "revokePhone",
  "pairedComputers",
  "computersOverview",
  "pairComputer",
  "forgetComputer",
  "handoffTargets",
  "handOffThread",
  "retryHandoff",
  "handoffView",
  "handoffViews",
  "bringBackThread",
  "keepThreadHere",
  "updateComputer",
] as const satisfies readonly ApiMethod[];
// Fails to compile, naming the method, when the Api gains one this list lacks.
const complete: Exclude<ApiMethod, (typeof methods)[number]> extends never
  ? true
  : Exclude<ApiMethod, (typeof methods)[number]> = true;
void complete;
const api = Object.fromEntries(
  methods.map((method) => [
    method,
    async (...args: unknown[]) => {
      const r = await ipcRenderer.invoke("relay:invoke", method, args);
      if (!r.ok) throw new Error(r.error);
      return r.value;
    },
  ]),
);
const subscribe =
  <T = unknown>(channel: string) =>
  (callback: (value: T) => void) => {
    const listener = (_event: unknown, value: T) => callback(value);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  };
const on = <C extends keyof RelayEvents>(channel: C) =>
  subscribe<RelayEvents[C]>(channel);
contextBridge.exposeInMainWorld("relay", {
  ...api,
  pathForFile: (file: File) => webUtils.getPathForFile(file),
  onProjectChat: on("relay:project-chat"),
  onProjectChats: on("relay:project-chats"),
  onUpdate: subscribe("relay:update"),
  onDictationState: subscribe("relay:dictation"),
  onAgentVersions: subscribe("relay:agent-updates"),
  onTerminal: subscribe("relay:terminal"),
  onMaximized: subscribe<boolean>("relay:maximized"),
  onOpenUrl: subscribe<string>("relay:open-url"),
});
// Ports can't cross the context bridge; a window message can carry one.
ipcRenderer.on("relay:dictation-port", (event) => {
  window.postMessage(
    "relay:dictation-port",
    location.origin === "null" ? "*" : location.origin,
    event.ports,
  );
});
