import { createHash } from "node:crypto";
import { readdir, readFile, realpath, stat } from "node:fs/promises";
import {
  basename,
  dirname,
  extname,
  isAbsolute,
  join,
  relative,
} from "node:path";

/**
 * Finds the icon a project already chose for itself: the IDE icon, the app
 * bundle icon, the web manifest or favicon, then native app icon sets.
 * Stock template icons (Vite, Next, Create React App, Angular, Flutter) say
 * nothing about the project and are skipped, as are tiny, huge or oddly
 * shaped images. No match leaves the sidebar on its folder icon.
 */

const MAX_BYTES = 256 * 1024;
/** PNGs up to this size are accepted when they can be scaled down. */
const MAX_SHRINK_BYTES = 16 * 1024 * 1024;
const MIN_PIXELS = 32;
/** Decoding takes width × height × 4 bytes whatever the file size: 64 MiB here. */
const MAX_PIXELS = 4096;
const SKIPPED_DIRS = new Set([
  "node_modules",
  "vendor",
  "dist",
  "build",
  "out",
  "target",
  "coverage",
  "Pods",
  "DerivedData",
  "fixtures",
  "__fixtures__",
  "tmp",
]);
const MIME: Record<string, string> = {
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
};
/** Template file names that are never a project's own icon. */
const STOCK_NAMES = new Set([
  "vite.svg",
  "react.svg",
  "next.svg",
  "vercel.svg",
  "tauri.svg",
  "electron.svg",
  "nuxt.svg",
  "svelte.svg",
  "vue.svg",
]);
/** SHA-256 of icons generated by project templates. */
const STOCK_HASHES = new Set([
  // Vite: vite.svg and the newer favicon.svg bolt
  "4a748afd443918bb16591c834c401dae33e87861ab5dbad0811c3a3b4a9214fb",
  "61bc9a161de58248288e6905425d7180f0624c2865007b97d763fdac12043a66",
  // Next.js: favicon.ico and next.svg
  "2b8ad2d33455a8f736fc3a8ebf8f0bdea8848ad4c0db48a2833bd0f9cd775932",
  "55995dfad6ecb4945a1e856ddca03c5e16aa5bf13fd21b4df6a74ae79357bcfc",
  // React: Vite's react.svg, Create React App's favicon.ico, logo192/512 and logo.svg
  "35ef61ed53b323ae94a16a8ec659b3d0af3880698791133f23b084085ab1c2e5",
  "3d10f7da6c603178340081668c4ac5b3ae9743ca9a262ab0fcd312fbb9f48bdd",
  "c386396ec70db3608075b5fbfaac4ab1ccaa86ba05a68ab393ec551eb66c3e00",
  "9ea4f4da7050c0cc408926f6a39c253624e9babb1d43c7977cd821445a60b461",
  "6000b0e9b0b05b3f112de04f0d039768a1db63588ff9b6ef7099dbd71632f383",
  // Angular CLI favicon.ico, old and new
  "2d0a4f5a77c788b084919b1b8cad5713d9dfc3388ef29969c4cb66c28092e683",
  "b9ccbb7100e13ae95ac18a3a9ed00857f321b63b498f1fb7abab506fc1c40e99",
  // Flutter: web favicon and icons, iOS, macOS and Android launcher icons
  "7ab2525f4b86b65d3e4c70358a17e5a1aaf6f437f99cbcc046dad73d59bb9015",
  "3dce99077602f70421c1c6b2a240bc9b83d64d86681d45f2154143310c980be3",
  "baccb205ae45f0b421be1657259b4943ac40c95094ab877f3bcbe12cd544dcbe",
  "d2c842e22a9f4ec9d996b23373a905c88d9a203b220c5c151885ad621f974b5c",
  "6aee06cdcab6b2aef74b1734c4778f4421d2da100b0ff9e52b21b55240202929",
  "7770183009e914112de7d8ef1d235a6a30c5834424858e0d2f8253f6b8d31926",
  "3c34e1f298d0c9ea3455d46db6b7759c8211a49e9ec6e44b635fc5c87dfb4180",
  "6232e5815af17e25e0268b2fec7aea9e068cc92ec709e9605c2b31df4ff2a313",
  "0a91c6c1bf242e54ee179e34629e9ef3e8a6d286c0fce01e302280a8be9277e6",
  "416efd77cde932d42ef34168da24dd428a495b1f4f34bbbd125a18d2add186a2",
  "15591f03f31313af6fd644ed0512106cc04365130b8b73244f1cfa6dddfb4400",
]);
const WELL_KNOWN = [
  "favicon.svg",
  "favicon.png",
  "favicon.ico",
  "icon.svg",
  "icon.png",
  "logo.svg",
  "public/favicon.svg",
  "public/favicon.png",
  "public/favicon.ico",
  "public/icon.svg",
  "public/icon.png",
  "public/logo.svg",
  "static/favicon.svg",
  "static/favicon.png",
  "static/favicon.ico",
  "app/icon.svg",
  "app/icon.png",
  "app/favicon.ico",
  "src/app/icon.svg",
  "src/app/icon.png",
  "src/app/favicon.ico",
  "src/favicon.svg",
  "src/favicon.ico",
  "src/assets/favicon.svg",
  "src/assets/favicon.ico",
  "wwwroot/favicon.ico",
  "web/favicon.png",
  "assets/icon.svg",
  "assets/icon.png",
  "assets/logo.svg",
  "assets/logo.png",
  "resources/icon.svg",
  "resources/icon.png",
  "build/icon.svg",
  "build/icon.png",
];
const MANIFESTS = [
  "public/manifest.json",
  "public/site.webmanifest",
  "public/manifest.webmanifest",
  "static/manifest.json",
  "static/site.webmanifest",
  "web/manifest.json",
  "app/manifest.json",
  "manifest.json",
  "site.webmanifest",
];
const PAGES = [
  "index.html",
  "public/index.html",
  "src/index.html",
  "web/index.html",
  "src/app.html",
  "app/root.tsx",
  "app/routes/__root.tsx",
  "src/routes/__root.tsx",
];
const FRONTENDS = ["frontend", "src/frontend", "client", "web", "ui"];
const ANDROID = [
  "app/src/main/res",
  "android/app/src/main/res",
  "src-tauri/icons/android",
];

export interface ImageInfo {
  type: "svg" | "raster";
  width: number;
  height: number;
}

/** Reads an image's size from its header; null when it is not an image we render. */
export function imageInfo(bytes: Buffer, ext: string): ImageInfo | null {
  if (ext === ".svg") {
    const text = bytes.toString("utf8");
    const tag = /<svg\b[^>]*>/i.exec(text)?.[0];
    if (!tag) return null;
    const box =
      /\bviewBox\s*=\s*["']\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)/i.exec(
        tag,
      );
    const size = (name: string) =>
      Number(
        new RegExp(
          `\\b${name}\\s*=\\s*["']\\s*([\\d.]+)(px)?\\s*["']`,
          "i",
        ).exec(tag)?.[1],
      );
    const width = box ? Number(box[1]) : size("width"),
      height = box ? Number(box[2]) : size("height");
    // An SVG without any size scales freely; treat it as square.
    return width > 0 && height > 0
      ? { type: "svg", width, height }
      : { type: "svg", width: 1, height: 1 };
  }
  if (ext === ".png") {
    if (
      bytes.length < 24 ||
      !bytes
        .subarray(0, 8)
        .equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))
    )
      return null;
    return {
      type: "raster",
      width: bytes.readUInt32BE(16),
      height: bytes.readUInt32BE(20),
    };
  }
  if (ext === ".ico") {
    if (
      bytes.length < 6 ||
      bytes.readUInt16LE(0) !== 0 ||
      bytes.readUInt16LE(2) !== 1
    )
      return null;
    let width = 0,
      height = 0;
    const count = bytes.readUInt16LE(4);
    for (let i = 0; i < count && 6 + i * 16 + 16 <= bytes.length; i++) {
      const w = bytes[6 + i * 16] || 256,
        h = bytes[7 + i * 16] || 256;
      if (w * h > width * height) [width, height] = [w, h];
    }
    return width ? { type: "raster", width, height } : null;
  }
  if (ext === ".webp") {
    if (bytes.length < 30 || bytes.toString("ascii", 0, 4) !== "RIFF")
      return null;
    const chunk = bytes.toString("ascii", 12, 16);
    if (chunk === "VP8X")
      return {
        type: "raster",
        width: bytes.readUIntLE(24, 3) + 1,
        height: bytes.readUIntLE(27, 3) + 1,
      };
    if (chunk === "VP8L") {
      const bits = bytes.readUInt32LE(21);
      return {
        type: "raster",
        width: (bits & 0x3fff) + 1,
        height: ((bits >> 14) & 0x3fff) + 1,
      };
    }
    if (chunk === "VP8 ")
      return {
        type: "raster",
        width: bytes.readUInt16LE(26) & 0x3fff,
        height: bytes.readUInt16LE(28) & 0x3fff,
      };
  }
  return null;
}

/** First `<link rel="icon" href>` in HTML or icon metadata in route source. */
export function iconHref(source: string): string | null {
  for (const tag of source.match(/<link\b[^>]*>/gi) ?? []) {
    if (!/\brel\s*=\s*["'](?:shortcut\s+)?icon["']/i.test(tag)) continue;
    const href = /\bhref\s*=\s*["']([^"']+)["']/i.exec(tag)?.[1];
    if (href) return href;
  }
  for (const run of source.split("}")) {
    if (!/\brel\s*:\s*["'](?:shortcut\s+)?icon["']/i.test(run)) continue;
    const href = /\bhref\s*:\s*["']([^"']+)["']/i.exec(run)?.[1];
    if (href) return href;
  }
  return null;
}

interface Found {
  path: string;
  info: ImageInfo;
  dataUrl: string;
}

/** Scales a large PNG down to a small PNG data URL; null when it cannot. */
export type Shrink = (path: string) => string | null;

async function readJson(path: string): Promise<unknown> {
  try {
    return JSON.parse(await readFile(path, "utf8"));
  } catch {
    return null;
  }
}

class Search {
  constructor(
    readonly root: string,
    private readonly shrink?: Shrink,
  ) {}

  /** Checks one file: inside the project, a real image, not stock, sensibly sized. */
  async check(path: string): Promise<Found | null> {
    const ext = extname(path).toLowerCase();
    if (!MIME[ext] || STOCK_NAMES.has(basename(path).toLowerCase()))
      return null;
    try {
      const real = await realpath(path);
      const rel = relative(this.root, real);
      if (!rel || rel.startsWith("..") || isAbsolute(rel)) return null;
      const info = await stat(real);
      const large = info.size > MAX_BYTES;
      if (
        !info.isFile() ||
        info.size === 0 ||
        (large && (ext !== ".png" || !this.shrink)) ||
        info.size > MAX_SHRINK_BYTES
      )
        return null;
      const bytes = await readFile(real);
      if (STOCK_HASHES.has(createHash("sha256").update(bytes).digest("hex")))
        return null;
      const image = imageInfo(bytes, ext);
      if (!image) return null;
      const ratio = image.width / image.height;
      if (ratio < 0.8 || ratio > 1.25) return null;
      if (
        image.type === "raster" &&
        (Math.min(image.width, image.height) < MIN_PIXELS ||
          Math.max(image.width, image.height) > MAX_PIXELS)
      )
        return null;
      const dataUrl = large
        ? this.shrink!(real)
        : `data:${MIME[ext]};base64,${bytes.toString("base64")}`;
      return dataUrl ? { path: real, info: image, dataUrl } : null;
    } catch {
      return null;
    }
  }

  async first(paths: string[]) {
    for (const path of paths) {
      const found = await this.check(path);
      if (found) return found;
    }
    return null;
  }

  /** The best of a set of sizes of one icon: SVG, else the largest raster. */
  async best(paths: string[]) {
    let best: Found | null = null;
    for (const path of paths) {
      const found = await this.check(path);
      if (!found) continue;
      if (found.info.type === "svg") return found;
      if (!best || found.info.width > best.info.width) best = found;
    }
    return best;
  }

  /** Icon paths named in package.json for electron-builder. */
  async packageIcons(base: string) {
    const pkg = (await readJson(join(base, "package.json"))) as {
      build?: Record<string, unknown>;
    } | null;
    const build = pkg?.build;
    if (!build || typeof build !== "object") return null;
    const icons = [
      build.icon,
      ...["mac", "linux", "win"].map(
        (k) => (build[k] as { icon?: unknown })?.icon,
      ),
    ].filter((icon): icon is string => typeof icon === "string");
    // .icns and .ico bundles usually sit beside a source SVG or PNG.
    return this.best(
      icons.flatMap((icon) => {
        const path = join(base, icon),
          stem = path.slice(0, path.length - extname(path).length);
        return [path, `${stem}.svg`, `${stem}.png`];
      }),
    );
  }

  /** Tauri 2 keeps the list under `bundle`, Tauri 1 under `tauri.bundle`. */
  async tauriIcons(base: string) {
    const conf = (await readJson(join(base, "src-tauri/tauri.conf.json"))) as {
      bundle?: { icon?: unknown };
      tauri?: { bundle?: { icon?: unknown } };
    } | null;
    const icons = conf?.bundle?.icon ?? conf?.tauri?.bundle?.icon;
    if (!Array.isArray(icons)) return null;
    return this.best(
      icons
        .filter((i): i is string => typeof i === "string")
        .map((i) => join(base, "src-tauri", i)),
    );
  }

  async manifestIcons(base: string) {
    for (const name of MANIFESTS) {
      const manifest = (await readJson(join(base, name))) as {
        icons?: unknown;
      } | null;
      if (!Array.isArray(manifest?.icons)) continue;
      const dir = dirname(join(base, name));
      const found = await this.best(
        manifest.icons
          .map((icon: { src?: unknown }) => icon?.src)
          .filter(
            (src): src is string =>
              typeof src === "string" && !/^[a-z]+:/i.test(src),
          )
          .map((src) => join(dir, src.split(/[?#]/)[0].replace(/^\//, ""))),
      );
      if (found) return found;
    }
    return null;
  }

  async linkedIcon(base: string) {
    for (const name of PAGES) {
      let source: string;
      try {
        source = await readFile(join(base, name), "utf8");
      } catch {
        continue;
      }
      const href = iconHref(source.slice(0, 200_000));
      if (!href || /^[a-z]+:|^\/\//i.test(href)) continue;
      const clean = href
        .split(/[?#]/)[0]
        .replace(/^%PUBLIC_URL%|^%sveltekit\.assets%/, "")
        .replace(/^\.?\//, "");
      const found = await this.first([
        join(base, "public", clean),
        join(base, "static", clean),
        join(base, dirname(name), clean),
        join(base, clean),
      ]);
      if (found) return found;
    }
    return null;
  }

  /** An `AppIcon.appiconset`, usually inside `*.xcassets`, a few levels down. */
  async appIconSet(base: string) {
    const queue: [string, number][] = [[base, 0]];
    let visited = 0;
    while (queue.length && visited < 400) {
      const [dir, depth] = queue.shift()!;
      visited++;
      let entries;
      try {
        entries = await readdir(dir, { withFileTypes: true });
      } catch {
        continue;
      }
      for (const entry of entries) {
        if (
          !entry.isDirectory() ||
          entry.name.startsWith(".") ||
          SKIPPED_DIRS.has(entry.name)
        )
          continue;
        const path = join(dir, entry.name);
        if (entry.name === "AppIcon.appiconset") {
          const found = await this.iconSet(path);
          if (found) return found;
        } else if (entry.name.endsWith(".xcassets")) {
          const found = await this.iconSet(join(path, "AppIcon.appiconset"));
          if (found) return found;
        } else if (depth < 4) queue.push([path, depth + 1]);
      }
    }
    return null;
  }

  async iconSet(dir: string) {
    const contents = (await readJson(join(dir, "Contents.json"))) as {
      images?: { filename?: unknown }[];
    } | null;
    const files = (contents?.images ?? [])
      .map((image) => image.filename)
      .filter((f): f is string => typeof f === "string" && !f.includes("/"));
    // A stock set is recognised by any of its sizes, not only the one shown.
    for (const file of files) {
      try {
        const bytes = await readFile(join(dir, file));
        if (STOCK_HASHES.has(createHash("sha256").update(bytes).digest("hex")))
          return null;
      } catch {
        // Missing sizes are common; the rest still count.
      }
    }
    // The sidebar icon is small: take the smallest size of at least 64px.
    const found = (
      await Promise.all(files.map((f) => this.check(join(dir, f))))
    ).filter((f): f is Found => !!f);
    return (
      found
        .filter((f) => f.info.width >= 64)
        .sort((a, b) => a.info.width - b.info.width)[0] ??
      found.sort((a, b) => b.info.width - a.info.width)[0] ??
      null
    );
  }

  async androidIcon(base: string) {
    return this.first(
      ANDROID.flatMap((res) =>
        ["xxxhdpi", "xxhdpi", "xhdpi"].flatMap((density) =>
          ["ic_launcher.png", "ic_launcher.webp"].map((file) =>
            join(base, res, `mipmap-${density}`, file),
          ),
        ),
      ),
    );
  }

  /** Every source, from the most deliberate choice to the most conventional. */
  async in(base: string) {
    return (
      (await this.first([
        join(base, ".idea/icon.svg"),
        join(base, ".idea/icon.png"),
      ])) ??
      (await this.packageIcons(base)) ??
      (await this.tauriIcons(base)) ??
      (await this.manifestIcons(base)) ??
      (await this.linkedIcon(base)) ??
      (await this.first(WELL_KNOWN.map((path) => join(base, path)))) ??
      (await this.appIconSet(base)) ??
      (await this.androidIcon(base))
    );
  }

  /** Monorepos keep their apps one level down, other repos their frontend. */
  async workspaces() {
    const apps: string[] = [];
    for (const group of ["apps", "packages"]) {
      try {
        for (const entry of await readdir(join(this.root, group), {
          withFileTypes: true,
        }))
          if (entry.isDirectory() && !entry.name.startsWith("."))
            apps.push(join(this.root, group, entry.name));
      } catch {
        // No such group.
      }
    }
    return [
      ...FRONTENDS.map((dir) => join(this.root, dir)),
      ...apps.sort().slice(0, 24),
    ];
  }
}

/** Finds a project's own icon as a data URL, or null to keep the folder icon. */
export async function findProjectIcon(root: string, shrink?: Shrink) {
  const search = new Search(await realpath(root), shrink);
  for (const base of [search.root, ...(await search.workspaces())]) {
    const found = await search.in(base);
    if (found) return { path: found.path, dataUrl: found.dataUrl };
  }
  return null;
}

const cache = new Map<string, { at: number; value: string | null }>();

/** Cached for five minutes when found and one when not, so new icons show up. */
export async function projectIcon(
  root: string,
  shrink?: Shrink,
): Promise<string | null> {
  const hit = cache.get(root);
  if (hit && Date.now() - hit.at < (hit.value ? 300_000 : 60_000))
    return hit.value;
  const value = (await findProjectIcon(root, shrink))?.dataUrl ?? null;
  cache.set(root, { at: Date.now(), value });
  return value;
}
