import type { FilePair } from "../../shared/types";
import type { WorkingChange } from "../../shared/working-tree";

export const changes: WorkingChange[] = [
  { path: "src/features/billing/Invoice.tsx", index: " ", worktree: "M", conflict: false },
  { path: "src/features/billing/invoice.css", index: " ", worktree: "M", conflict: false },
  { path: "src/lib/api.ts", index: "M", worktree: " ", conflict: false },
  { path: "src/features/billing/useTotals.ts", index: "?", worktree: "?", conflict: false },
];

export interface IgnoredTouch {
  path: string;
  /** The rule `git check-ignore -v` names. */
  rule: { source: string; line: number; pattern: string };
  /** Who wrote it last, and when in the thread. */
  by: string;
  /** No snapshot means the agent made the file. */
  before: string | null;
  now: string;
}

export const touched: IgnoredTouch[] = [
  {
    path: ".env.local",
    rule: { source: ".gitignore", line: 4, pattern: ".env*.local" },
    by: "Claude · turn 3",
    before: [
      "# Sample values",
      "API_URL=http://localhost:4000",
      "STRIPE_KEY=sk_test_sample_old",
      "FEATURE_INVOICES=false",
      "",
    ].join("\n"),
    now: [
      "# Sample values",
      "API_URL=http://localhost:4000",
      "STRIPE_KEY=sk_test_sample_old",
      "FEATURE_INVOICES=true",
      "INVOICE_PDF_WORKER=http://localhost:4100",
      "",
    ].join("\n"),
  },
  {
    path: "src/generated/billing-client.ts",
    rule: { source: ".gitignore", line: 11, pattern: "src/generated/" },
    by: "Claude · turn 4",
    before: [
      "// Generated by openapi-gen. Do not edit.",
      "export interface Invoice {",
      "  id: string;",
      "  total: number;",
      "}",
      "",
      "export const getInvoice = (id: string) =>",
      "  request<Invoice>(`/invoices/${id}`);",
      "",
    ].join("\n"),
    now: [
      "// Generated by openapi-gen. Do not edit.",
      "export interface Invoice {",
      "  id: string;",
      "  total: number;",
      "  currency: string;",
      "  lines: InvoiceLine[];",
      "}",
      "",
      "export interface InvoiceLine {",
      "  label: string;",
      "  amount: number;",
      "}",
      "",
      "export const getInvoice = (id: string) =>",
      "  request<Invoice>(`/invoices/${id}`);",
      "",
    ].join("\n"),
  },
  {
    path: "playwright/.auth/state.json",
    rule: { source: ".git/info/exclude", line: 2, pattern: "playwright/.auth/" },
    by: "Codex · turn 5",
    before: null,
    now: JSON.stringify(
      { cookies: [{ name: "session", value: "sample", domain: "localhost" }], origins: [] },
      null,
      2,
    ) + "\n",
  },
];

const side = (name: string, contents: string) => ({ name, contents, cacheKey: `${name}:${contents.length}` });

export const pairFor = (t: IgnoredTouch): FilePair => ({
  old: t.before === null ? null : side(t.path, t.before),
  next: side(t.path, t.now),
  binary: false,
});

const tracked: Record<string, [string, string]> = {
  "src/features/billing/Invoice.tsx": [
    "export function Invoice({ invoice }: Props) {\n  return <h2>{invoice.id}</h2>;\n}\n",
    "export function Invoice({ invoice }: Props) {\n  return (\n    <section className=\"invoice\">\n      <h2>{invoice.id}</h2>\n      <InvoiceLines lines={invoice.lines} />\n    </section>\n  );\n}\n",
  ],
};
export const trackedPair = (path: string): FilePair => {
  const [old, next] = tracked[path] ?? ["// before\n", "// after\n"];
  return { old: side(path, old), next: side(path, next), binary: false };
};
