// The phone app's runtime: a fingerprint of everything native, so a bundle a
// desktop hands out only runs on an APK built from the same native side.
// Versions and `extra` are left out: they change with every release while the
// native code often doesn't. Prints it when run directly.
import { createFingerprintAsync, SourceSkips } from "@expo/fingerprint";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const mobileRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export async function phoneRuntime() {
  // app.config.js reads these; the fingerprint must not see a release's values.
  for (const name of ["RELAY_VERSION", "RELAY_VERSION_CODE", "RELAY_RUNTIME"]) delete process.env[name];
  const { hash } = await createFingerprintAsync(mobileRoot, {
    platforms: ["android"],
    sourceSkips: SourceSkips.ExpoConfigVersions | SourceSkips.ExpoConfigExtraSection,
    // Generated by prebuild; CI fingerprints before it exists.
    ignorePaths: ["android/**/*", "ios/**/*"],
  });
  return hash;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) console.log(await phoneRuntime());
