import { describe, expect, it } from "vitest";
import { filePathInInlineCode, resolveFileLink } from "./markdown-links";

describe("inline code candidates", () => {
  it.each<[string, string | null]>([
    ["a.ts", null],
    ["README", null],
    ["node.meta", null],
    ["a.ts:3", "a.ts:3"],
    ["a.ts:3:4:5", "a.ts:3:4:5"],
    ["Makefile:3", "Makefile:3"],
    ["src/a.ts", "src/a.ts"],
    ["  src/a.ts  ", "src/a.ts"],
    ["src/a b.ts", null],
    ["foo bar", null],
    ["src/`a`.ts", null],
    ["./a.ts", "./a.ts"],
    ["./x", "./x"],
    ["~/a.ts", "~/a.ts"],
    ["~/", "~/"],
    ["/", "/"],
    ["/etc/hosts", "/etc/hosts"],
    ["/Users/me/a.ts#L5", "/Users/me/a.ts#L5"],
    ["C:/x/y.ts", "C:/x/y.ts"],
    ["C:\\x\\y.ts", "C:\\x\\y.ts"],
    ["src\\a\\b.ts", "src/a/b.ts"],
    ["..\\a.ts", "../a.ts"],
    ["example.com/x", null],
    ["example.com/x.html", null],
    ["localhost/a.ts", null],
    ["localhost:3000", null],
    ["1.2.3/a.ts", null],
    ["my-app.io/x.ts", null],
    ["foo.com:3", null],
    ["foo.pl:3", "foo.pl:3"],
    ["foo.pl/x.ts", null],
    ["foo.de", null],
    ["port:3000", "port:3000"],
    ["error:1", "error:1"],
    ["a.b.c/d.ts", "a.b.c/d.ts"],
    ["x/y.com", "x/y.com"],
    [".github/x.yml", ".github/x.yml"],
    ["src/.hidden", "src/.hidden"],
    ["src/dir", null],
    ["src/Makefile", null],
    ["a/b", null],
    ["a/b/", null],
    ["src/a.ts:", null],
    ["src/a.ts:0", "src/a.ts:0"],
    ["src/a.ts#L3", null],
    ["http://a/b.ts", "http://a/b.ts"],
    ["", null],
  ])("%j gives %j", (input, expected) => {
    expect(filePathInInlineCode(input)).toBe(expected);
  });

  it("leaves positions and odd shapes for the link parser to reject", () => {
    for (const text of ["a.ts:3:4:5", "port:3000", "error:1", "http://a/b.ts"])
      expect(resolveFileLink(filePathInInlineCode(text)!)).toBe(null);
  });
});

describe("link destinations", () => {
  it.each<[string, object | null]>([
    ["src/a.ts", { path: "src/a.ts" }],
    ["<src/a b.ts>", { path: "src/a b.ts" }],
    ["src/a%20b.ts", { path: "src/a b.ts" }],
    ["src/a.ts#L10", { path: "src/a.ts", line: 10 }],
    ["src/a.ts#L10C5", { path: "src/a.ts", line: 10, column: 5 }],
    ["src/a.ts#l10c5", { path: "src/a.ts", line: 10, column: 5 }],
    ["src/a.ts:10#L99", { path: "src/a.ts", line: 10 }],
    ["src/a.ts?x=1#L3", { path: "src/a.ts", line: 3 }],
    ["src/a.ts:007", { path: "src/a.ts", line: 7 }],
    ["src/a.ts#L0", { path: "src/a.ts" }],
    ["src/a.ts#L3-L5", { path: "src/a.ts" }],
    ["src/a.ts#L3C", { path: "src/a.ts" }],
    ["src/a.ts#frag", { path: "src/a.ts" }],
    ["a.ts:0", { path: "a.ts" }],
    ["a.ts:0:5", { path: "a.ts" }],
    ["a.ts:99999999999999999999", { path: "a.ts" }],
    [
      "/Users/test/workspace/a.ts:3:2",
      { path: "/Users/test/workspace/a.ts", line: 3, column: 2 },
    ],
    ["#L3", null],
    ["//x/y.ts", null],
    ["", null],
    ["   ", null],
    ["<>", null],
    ["/app/settings", null],
    ["/chat/settings#L3", null],
    ["/chat/settings:3", { path: "/chat/settings", line: 3 }],
    ["/foo/bar.ts", { path: "/foo/bar.ts" }],
    ["/tmp/x", { path: "/tmp/x" }],
    ["/foo/bar/", null],
    ["https://x.y/a.ts", null],
    ["mailto:a@b.c", null],
    ["tel:123", null],
    ["javascript:alert(1)", null],
    ["a.ts:3:4:5", null],
    ["a:b/c.ts", null],
    ["C:foo.ts", null],
    ["C:", null],
    ["localhost:3000", null],
    ["C:\\a.ts", { path: "C:\\a.ts" }],
    ["C:/a.ts", { path: "C:/a.ts" }],
    ["/C:/a.ts", { path: "C:/a.ts" }],
    ["file:///C:/a.ts", { path: "C:/a.ts" }],
    ["/c%3A/a.ts", { path: "c:/a.ts" }],
    [
      "file:///Users/test/workspace/a.ts",
      { path: "/Users/test/workspace/a.ts" },
    ],
    [
      "FILE:///Users/test/workspace/a.ts",
      { path: "/Users/test/workspace/a.ts" },
    ],
    ["file:/Users/test/workspace/a.ts", { path: "/Users/test/workspace/a.ts" }],
    [
      "file://LocalHost/Users/test/workspace/a.ts?q=1#L3C2",
      { path: "/Users/test/workspace/a.ts", line: 3, column: 2 },
    ],
    [
      "file:///Users/test/workspace/a%20b.ts:5",
      { path: "/Users/test/workspace/a b.ts", line: 5 },
    ],
    ["file:///root/src/../a.ts", { path: "/root/a.ts" }],
    ["file:///root/./src/./a.ts:4", { path: "/root/src/a.ts", line: 4 }],
    ["file:///../../a.ts", { path: "/a.ts" }],
    ["C://a.ts", { path: "C://a.ts" }],
    [".env", { path: ".env" }],
    ["file://host/share/a.ts", null],
    ["file:a.ts", null],
    ["file://localhost", null],
    ["Makefile", { path: "Makefile" }],
    ["Makefile:3", { path: "Makefile", line: 3 }],
    ["LICENSE", { path: "LICENSE" }],
    ["readme.md", { path: "readme.md" }],
    ["a b.ts", { path: "a b.ts" }],
    ["docs/a b/c.ts", { path: "docs/a b/c.ts" }],
    ["foo/bar", { path: "foo/bar" }],
    ["example.com/index.html", { path: "example.com/index.html" }],
    ["foo", null],
    ["src/dir/", null],
    ["src//a.ts", null],
    ["src\\a.ts", null],
    [".\\a.ts", null],
    ["docs/é.ts", null],
    ["é.ts", null],
    ["app/routes/", null],
    ["docs/ a.ts", null],
    ["./x", { path: "./x" }],
    ["./", { path: "./" }],
    ["../x.ts", { path: "../x.ts" }],
    ["~/x.ts", { path: "~/x.ts" }],
    ["src/../x.ts", { path: "src/../x.ts" }],
    ["src/%2e%2e/x.ts", { path: "src/../x.ts" }],
    ["/Users/test/workspace/src/", { path: "/Users/test/workspace/src/" }],
    ["/Users/me/a%3Fb%23L3.ts", { path: "/Users/me/a?b#L3.ts" }],
    ["src/a.ts%", null],
    ["%E0%A4%A", null],
  ])("%j gives %j", (href, expected) => {
    expect(resolveFileLink(href)).toEqual(expected);
  });

  it("never throws", () => {
    for (const odd of [
      "<",
      ">",
      "%",
      "file:",
      "file://",
      "file:///",
      ":" + "9".repeat(400),
      "a.ts:" + "9".repeat(400) + ":" + "9".repeat(400),
      "src/\0.ts",
      "src/😅.ts",
      "\uD800",
      "%uD800",
    ]) {
      expect(() => resolveFileLink(odd)).not.toThrow();
      expect(() => filePathInInlineCode(odd)).not.toThrow();
    }
  });
});
